services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ocr
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: invoices
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ollama_data:
  pgdata: